### ISSUE TITLE
get global emotes for bttv/ffz/7tv

### ISSUE THREAD

**Issue by mattyHerzig** [teklynk/twitch_api_public#12]
Currently in `./public` there's `getglobalemotes.php`, `getuseremotes.php`, `getbttvemotes.php`, `getffzemotes.php`, and `get7tvemotes.php`. What about `getglobalbttvemotes.php`, `getglobalffzemotes.php`, or `getglobal7tvemotes.php`? Thanks

**Comment by teklynk** [comment]
Hello,
The getglobalbttvemotes.php and getglobalffzemotes.php already includes the global emotes along with the users custom emotes. This can be seen in the code here: https://github.com/teklynk/twitch_api_public/blob/main/public/getbttvemotes.php and https://github.com/teklynk/twitch_api_public/blob/main/public/getffzemotes.php
 
I recently removed global emotes from 7TV since I do not think they offer a way to get those in V3 of thier API. You used to be able to get those from https://api.7tv.app/v2/emotes/global but it is down and V3 https://7tv.io/v3/emotes/global does not work (returns: Bad Request).

**Comment by mattyHerzig** [comment]
ah, thanks! not that it matters much, but if you do want sort of a hacky way to get the 7TV global emotes with V3 of their API, maybe you can use the Get Emote Set API call on something like [this](https://7tv.app/emote-sets/62cdd34e72a832540de95857)?

**Comment by teklynk** [comment]
Thank you!

I think that works! I added https://7tv.io/v3/emote-sets/62cdd34e72a832540de95857 as the api endpoint to get the global emotes.
