### ISSUE TITLE
getuserclips.php does not return newer clips

### ISSUE THREAD

**Issue by Snoozaya** [teklynk/twitch_api_public#13]
When calling https://twitchapi.teklynk.com/getuserclips.php?channel=<channelname>, it will only return clips older than ~2 months.

I discovered this issue when attempting to fetch clips for the twitch channel "Sethiduck", which will always return the 3 oldest clips, despite there being 8 clips in total.

I would be very grateful for a fix. I assume it might be related to recent changes to clips on Twitch.

**Comment by teklynk** [comment]
Hello. There have been a few changes by Twitch in how clips are served. As a work-around, I limited my custom Clips API to only show clips that use the old clip URL. Here is the original issue: https://github.com/teklynk/twitch_clips_player/issues/13

The way these clips overlays get the clip's MP4 file was never officially supported by Twitch. It was something that someone figured out, and other developers seemed to adopt. I am hoping that Twitch provides an official way to grab the MP4 or stream the clips via HLS/M3U8. Currently, I have not found a solution other than rewriting the Clips Player overlay to launch an iframe with the embedded Twitch player, which is not pretty.

I have seen that Twitchguru has a solution. I think they are using a separate server that launches a web browser and scrapes the HTML using something like Selenium to grab the clip URL containing the unique GraphQL token. This probably means that they are paying for a Windows Server with a desktop environment to achieve this. Twitchguru does charge for some of their tools, so maybe they can afford this solution? Or maybe they have to in order to keep their customers?

I will keep an eye out for solutions that other devs come up with. For now, most devs are dealing with the same situation.

**Comment by teklynk** [comment]
@Snoozaya 

This "should" now be fixed but I do not know for how long since it uses yet another un-official way to get the clips from Twitch. With some help from the community and some reverse engineering we were able to figure out Twitch's (undocumented) graphql query. This however uses Twitch's client-id and graphql token. I do not know if Twitch will ever change these tokens over time. For now, It seems to be working!
